# ==========================
# Foot
# ==========================

[main]
font=monospace:size=14
pad=10x10
dpi-aware=yes

# Cursor
[cursor]
style=beam
blink=yes


# ==========================
# Colors
# ==========================

[colors]
foreground=202020
background=fafafa
alpha=0.7


selection-foreground=fafafa
selection-background=202020

regular0=2e2e2e
regular1=c0392b
regular2=27ae60
regular3=f39c12
regular4=2980b9
regular5=8e44ad
regular6=16a085
regular7=ecf0f1

bright0=7f8c8d
bright1=e74c3c
bright2=2ecc71
bright3=f1c40f
bright4=3498db
bright5=9b59b6
bright6=1abc9c
bright7=ffffff

# ==========================
# Scrollback
# ==========================

[scrollback]
lines=10000


# ==========================
# Window
# ==========================

[bell]
urgent=yes

[csd]
preferred=none